# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/imhikarucat/Desktop/CPP/asn2-att2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/imhikarucat/Desktop/CPP/asn2-att2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/imhikarucat/Desktop/CPP/asn2-att2/CMakeFiles /Users/imhikarucat/Desktop/CPP/asn2-att2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/imhikarucat/Desktop/CPP/asn2-att2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mazer

# Build rule for target.
mazer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mazer
.PHONY : mazer

# fast build rule for target.
mazer/fast:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/build
.PHONY : mazer/fast

Coordinator.o: Coordinator.cpp.o

.PHONY : Coordinator.o

# target to build an object file
Coordinator.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Coordinator.cpp.o
.PHONY : Coordinator.cpp.o

Coordinator.i: Coordinator.cpp.i

.PHONY : Coordinator.i

# target to preprocess a source file
Coordinator.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Coordinator.cpp.i
.PHONY : Coordinator.cpp.i

Coordinator.s: Coordinator.cpp.s

.PHONY : Coordinator.s

# target to generate assembly for a file
Coordinator.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Coordinator.cpp.s
.PHONY : Coordinator.cpp.s

Edge.o: Edge.cpp.o

.PHONY : Edge.o

# target to build an object file
Edge.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Edge.cpp.o
.PHONY : Edge.cpp.o

Edge.i: Edge.cpp.i

.PHONY : Edge.i

# target to preprocess a source file
Edge.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Edge.cpp.i
.PHONY : Edge.cpp.i

Edge.s: Edge.cpp.s

.PHONY : Edge.s

# target to generate assembly for a file
Edge.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Edge.cpp.s
.PHONY : Edge.cpp.s

GrowingTree.o: GrowingTree.cpp.o

.PHONY : GrowingTree.o

# target to build an object file
GrowingTree.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/GrowingTree.cpp.o
.PHONY : GrowingTree.cpp.o

GrowingTree.i: GrowingTree.cpp.i

.PHONY : GrowingTree.i

# target to preprocess a source file
GrowingTree.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/GrowingTree.cpp.i
.PHONY : GrowingTree.cpp.i

GrowingTree.s: GrowingTree.cpp.s

.PHONY : GrowingTree.s

# target to generate assembly for a file
GrowingTree.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/GrowingTree.cpp.s
.PHONY : GrowingTree.cpp.s

HuntAndKill.o: HuntAndKill.cpp.o

.PHONY : HuntAndKill.o

# target to build an object file
HuntAndKill.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/HuntAndKill.cpp.o
.PHONY : HuntAndKill.cpp.o

HuntAndKill.i: HuntAndKill.cpp.i

.PHONY : HuntAndKill.i

# target to preprocess a source file
HuntAndKill.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/HuntAndKill.cpp.i
.PHONY : HuntAndKill.cpp.i

HuntAndKill.s: HuntAndKill.cpp.s

.PHONY : HuntAndKill.s

# target to generate assembly for a file
HuntAndKill.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/HuntAndKill.cpp.s
.PHONY : HuntAndKill.cpp.s

Maze.o: Maze.cpp.o

.PHONY : Maze.o

# target to build an object file
Maze.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Maze.cpp.o
.PHONY : Maze.cpp.o

Maze.i: Maze.cpp.i

.PHONY : Maze.i

# target to preprocess a source file
Maze.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Maze.cpp.i
.PHONY : Maze.cpp.i

Maze.s: Maze.cpp.s

.PHONY : Maze.s

# target to generate assembly for a file
Maze.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Maze.cpp.s
.PHONY : Maze.cpp.s

Prim.o: Prim.cpp.o

.PHONY : Prim.o

# target to build an object file
Prim.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Prim.cpp.o
.PHONY : Prim.cpp.o

Prim.i: Prim.cpp.i

.PHONY : Prim.i

# target to preprocess a source file
Prim.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Prim.cpp.i
.PHONY : Prim.cpp.i

Prim.s: Prim.cpp.s

.PHONY : Prim.s

# target to generate assembly for a file
Prim.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/Prim.cpp.s
.PHONY : Prim.cpp.s

RecursiveBacktracking.o: RecursiveBacktracking.cpp.o

.PHONY : RecursiveBacktracking.o

# target to build an object file
RecursiveBacktracking.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/RecursiveBacktracking.cpp.o
.PHONY : RecursiveBacktracking.cpp.o

RecursiveBacktracking.i: RecursiveBacktracking.cpp.i

.PHONY : RecursiveBacktracking.i

# target to preprocess a source file
RecursiveBacktracking.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/RecursiveBacktracking.cpp.i
.PHONY : RecursiveBacktracking.cpp.i

RecursiveBacktracking.s: RecursiveBacktracking.cpp.s

.PHONY : RecursiveBacktracking.s

# target to generate assembly for a file
RecursiveBacktracking.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/RecursiveBacktracking.cpp.s
.PHONY : RecursiveBacktracking.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/mazer.dir/build.make CMakeFiles/mazer.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mazer"
	@echo "... Coordinator.o"
	@echo "... Coordinator.i"
	@echo "... Coordinator.s"
	@echo "... Edge.o"
	@echo "... Edge.i"
	@echo "... Edge.s"
	@echo "... GrowingTree.o"
	@echo "... GrowingTree.i"
	@echo "... GrowingTree.s"
	@echo "... HuntAndKill.o"
	@echo "... HuntAndKill.i"
	@echo "... HuntAndKill.s"
	@echo "... Maze.o"
	@echo "... Maze.i"
	@echo "... Maze.s"
	@echo "... Prim.o"
	@echo "... Prim.i"
	@echo "... Prim.s"
	@echo "... RecursiveBacktracking.o"
	@echo "... RecursiveBacktracking.i"
	@echo "... RecursiveBacktracking.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

